### PR TITLE
activities/GitHub Quiz 1.0.md

### PR DESCRIPTION
**Pull request by anurag-majumdar**
Hi @danivijay , added the GitHub Quiz 1.0 to the repository. Let me know if its good to go. Thanks in advance.

### CODE REVIEW

**Comment by anurag-majumdar** [comment]
@ashwani99 @danivijay  I will be adding the part 2 and 3 of the quiz later on as separately due to lack of time. Please accept my PR for now. Thanks in advance.

**Comment by ashwani99** [comment]
@anurag-majumdar Okay, please resolve the conflicts and its good to merge

**Comment by anurag-majumdar** [comment]
@ashwani99 Resolved conflicts. Ready for merge with master.

**Comment by ashwani99** [comment]
@anurag-majumdar Merged. Thanks for your contribution!

**Comment by anurag-majumdar** [comment]
@ashwani99 Thanks for the heads up. 😃

**Pull request merged**
